myApp:
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    bucketName: ${env.bucket}
    domain: ${env.domain}
    cloudfront:
      distributionId: ${env.cloudfront-distro}
    certificate:
        cloudFrontDefaultCertificate: false
        acmCertificateArn: ${env.acm}
    name: ${env.function}